########################### NETWORK
networks:
  web:
    external: true
  internal:
    external: false

########################### SERVICES
services:
  webauspex-jupyterlite:
    build: .
    volumes:
      - ./notebooks:/app/notebooks
    restart: unless-stopped     
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webauspex-jupyterlite.rule=Host(`webauspex.app.pb.utfpr.edu.br`)"
      - "traefik.http.routers.webauspex-jupyterlite.entrypoints=websecure"
      - "traefik.http.routers.webauspex-jupyterlite.tls.certresolver=letsencrypt"
    ports:
      - 8633:8000
    networks:
      - web